#pragma once

namespace SMF
{
	enum class GMPatch : uint8_t
	{
		//Family: Piano
		ACOUSTIC_GRAND_PIANO			= 1,
		BRIGHT_ACOUSTIC_PIANO			= 2,
		ELECTRIC_GRAND_PIANO			= 3,
		HONKY_TONK_PIANO				= 4,
		ELECTRIC_PIANO_1				= 5,
		ELECTRIC_PIANO_2				= 6,
		HARPSICHORD						= 7,
		CLAVINET						= 8,
		//Family: Chromatic Percussion
		CELESTA							= 9,
		GLOCKENSPIEL					= 10,
		MUSIC_BOX						= 11,
		VIBRAPHONE						= 12,
		MARIMBA							= 13,
		XYLOPHONE						= 14,
		TUBULAR_BELLS					= 15,
		DULCIMER						= 16,
		//Family: Organ
		DRAWBAR_ORGAN_HAMMOND			= 17,
		PERCUSSIVE_ORGAN				= 18,
		ROCK_ORGAN						= 19,
		CHURCH_ORGAN					= 20,
		REED_ORGAN						= 21,
		ACCORDION_FRENCH				= 22,
		HARMONICA						= 23,
		TANGO_ACCORDION					= 24,
		//Family: Guitar
		NYLON_ACOUSTIC_GUITAR			= 25,
		STEEL_ACOUSTIC_GUITAR			= 26,
		JAZZ_ELECTRIC_GUITAR			= 27,
		CLEAN_ELECTRIC_GUITAR			= 28,
		MUTED_ELECTRIC_GUITAR			= 29,
		OVERDRIVEN_GUITAR				= 30,
		DISTORTION_GUITAR				= 31,
		GUITAR_HARMONICA				= 32,
		//Family: Bass
		ACOUSTIC_BASS					= 33,
		FINGERED_ELECTRIC_BASS			= 34,
		PICKED_ELECTRIC_BASS			= 35,
		FRETLESS_BASS					= 36,
		SLAP_BASS_1						= 37,
		SLAP_BASS_2						= 38,
		SYNTH_BASS_1					= 39,
		SYNTH_BASS_2					= 40,
		//Family: Strings
		VIOLIN							= 41,
		VIOLA							= 42,
		CELLO							= 43,
		CONTRABASS						= 44,
		TREMOLO_STRINGS					= 45,
		PIZZICATO_STRINGS				= 46,
		ORCHESTRAL_HARP					= 47,
		TIMPANI							= 48,
		//Family: Ensemble
		STRINGS_ENSEMBLE				= 49,
		SLOW_STRINGS_ENSEMBLE			= 50,
		SYNTHSTRINGS_1					= 51,
		SYNTHSTRINGS_2					= 52,
		CHOIR_AAHS						= 53,
		VOICE_OOHS						= 54,
		SYNTH_VOICE						= 55,
		//Family: Brass
		ORCHESTRA_HIT					= 56,
		TRUMPET							= 57,
		TROMBONE						= 58,
		TUBA							= 59,
		MUTED_TRUMPET					= 60,
		FRENCH_HORN						= 61,
		BRASS_SECTION					= 62,
		SYNTHBRASS_1					= 63,
		SYNTHBRASS_2					= 64,
		//Family: Reed
		SOPRANO_SAX						= 65,
		ALTO_SAX						= 66,
		TENOR_SAX						= 67,
		BARITONE_SAX					= 68,
		OBOE							= 69,
		ENGLISH_HORN					= 70,
		BASSOON							= 71,
		CLARINET						= 72,
		//Family: Pipe
		PICCOLO							= 73,
		FLUTE							= 74,
		RECORDER						= 75,
		PAN_FLUTE						= 76,
		BLOWN_BOTTLE					= 77,
		SKAKUHACHI						= 78,
		WHISTLE							= 79,
		OCARINA							= 80,
		//Family: Synth Lead
		SQUARE_WAVE						= 81,
		SAWTOOTH_WAVE					= 82,
		CALLIOPE						= 83,
		CHIFFER							= 84,
		CHARANG							= 85,
		VOICE_SOLO						= 86,
		FIFTHS							= 87,
		BASS_AND_LEAD					= 88,
		//Family: Synth Pad
		NEW_AGE_FANTASIA				= 89,
		WARM							= 90,
		POLYSYNTH						= 91,
		CHOIR_SPACE_VOICE				= 92,
		BOWED_GLASS						= 93,
		METALLIC_PRO					= 94,
		HALO							= 95,
		SWEEP							= 96,
		//Family: Synth Effects
		FX_RAIN							= 97,
		FX_SOUNDTRACK					= 98,
		FX_CRYSTAL						= 99,
		FX_ATMOSPHERE					= 100,
		FX_BRIGHTNESS					= 101,
		FX_GOBLINS						= 102,
		FX_ECHOES_DROPS					= 103,
		FX_SCI_FI_STAR_THEME			= 104,
		//Family: Ethnic
		SITAR							= 105,
		BANJO							= 106,
		SHAMISEN						= 107,
		KOTO							= 108,
		KALIMBA							= 109,
		BAG_PIPE						= 110,
		FIDDLE							= 111,
		SHANAI							= 112,
		//Family: Percussive
		TINKLE_BELL						= 113,
		AGOGO							= 114,
		STEEL_DRUMS						= 115,
		WOODBLOCK						= 116,
		TAIKO_DRUM						= 117,
		MELODIC_TOM						= 118,
		SYNTH_DRUM						= 119,
		//Family: Sound Effects
		REVERSE_CYMBAL					= 120,
		GUITAR_FRET_NOISE				= 121,
		BREATH_NOISE					= 122,
		SEASHORE						= 123,
		BIRD_TWEET						= 124,
		TELEPHONE_RING					= 125,
		HELICOPTER						= 126,
		APPLAUSE						= 127,
		GUNSHOT							= 128
	};
}